apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-prio
value: 100000
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: medium-prio
value: 1000
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-prio
value: 10
globalDefault: true
description: "Default priority class"